### ISSUE TITLE
アクセシビリティ: セマンティックHTMLとARIAラベルの改善

### ISSUE THREAD

**Issue by 6uclz1** [6uclz1/claude-code-blog-site#16]
## 問題

現在のWebサイトはアクセシビリティの観点で改善が必要です。スクリーンリーダーやキーボードナビゲーションに対応が不十分です。

## 現在の問題点

- セマンティックHTML要素の不足
- ARIAラベルが未実装
- フォーカス表示が不十分
- 見出し階層の整理が必要

## 提案する解決策

1. **セマンティック要素の追加**
   ```html
   <nav aria-label="メインナビゲーション">
   <main role="main">
   <article itemscope itemtype="http://schema.org/BlogPosting">
   ```

2. **ARIAラベルとキーボード対応**
   ```html
   <button aria-label="前のページ" aria-describedby="pagination-help">
   <nav aria-label="ページネーション">
   ```

3. **フォーカスインジケーターの追加**
   ```css
   a:focus, button:focus {
     outline: 2px solid #3498db;
     outline-offset: 2px;
   }
   ```

## 期待される効果
- スクリーンリーダー対応の向上
- キーボードナビゲーションの改善
- WCAG 2.1 AA準拠への前進

## 優先度
🟡 **中**

## 関連ファイル
- `_layouts/default.html`
- `_layouts/post.html` 
- `index.html`
- `assets/css/style.css`
