### ISSUE TITLE
テスト: 自動化スクリプトの単体テストとCIテストの追加

### ISSUE THREAD

**Issue by 6uclz1** [6uclz1/claude-code-blog-site#19]
## 問題

現在のプロジェクトには自動化されたテストが存在せず、コードの品質保証や回帰テストができていません。

## 不足している要素

- Pythonスクリプトの単体テスト
- Jekyll ビルドのテスト
- GitHub Actions でのテスト自動実行
- コードカバレッジの測定

## 提案する解決策

1. **Pythonテストフレームワークの追加**
   ```python
   # tests/test_fetch_and_summarize.py
   import pytest
   from scripts.fetch_and_summarize import HatenaBookmarkSummarizer
   
   def test_url_validation():
       # URLバリデーションのテスト
   
   def test_content_extraction():
       # コンテンツ抽出のテスト
   ```

2. **requirements-dev.txt の作成**
   ```
   pytest>=7.0.0
   pytest-cov>=4.0.0
   pytest-mock>=3.0.0
   ```

3. **GitHub Actions テストワークフロー**
   ```yaml
   # .github/workflows/test.yml
   name: Run Tests
   on: [push, pull_request]
   jobs:
     test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Run Python tests
           run: pytest --cov=scripts/
   ```

4. **Jekyll ビルドテスト**
   ```bash
   bundle exec jekyll build --strict_front_matter
   bundle exec jekyll doctor
   ```

## 期待される効果
- バグの早期発見
- リファクタリングの安全性向上
- コード品質の向上
- 継続的インテグレーション

## 優先度
🟢 **低**

## 関連ファイル
- `scripts/fetch_and_summarize.py`
- `requirements.txt` (テスト依存関係追加)
- `.github/workflows/test.yml` (新規作成)
- `tests/` (新規ディレクトリ)
