### ISSUE TITLE
監視: ログの構造化と監視機能の強化

### ISSUE THREAD

**Issue by 6uclz1** [6uclz1/claude-code-blog-site#20]
## 問題

現在の自動化スクリプトではログが基本的で、運用時の問題特定や監視が困難です。

## 現在の問題点

- 構造化ログが未実装
- 重要なメトリクスの記録が不足
- アラート機能がない
- ログレベルの細分化が不十分

## 提案する解決策

1. **構造化ログの実装**
   ```python
   import structlog
   
   logger = structlog.get_logger()
   logger.info("記事処理開始", 
              article_count=len(entries),
              processing_date=date.isoformat())
   ```

2. **メトリクス収集**
   ```python
   metrics = {
       "articles_processed": 0,
       "articles_failed": 0,
       "api_calls_made": 0,
       "processing_time": 0
   }
   ```

3. **GitHub Actions 通知**
   ```yaml
   - name: Notify on failure
     if: failure()
     uses: 8398a7/action-slack@v3
     with:
       status: failure
   ```

4. **ヘルスチェック機能**
   ```python
   def health_check():
       # API接続確認
       # RSS フィード確認
       # 最新投稿日時確認
   ```

## 期待される効果
- 問題の早期発見
- 運用の自動化
- パフォーマンス監視
- 障害対応の迅速化

## 優先度
🟡 **中**

## 関連ファイル
- `scripts/fetch_and_summarize.py`
- `.github/workflows/update-blog.yml`
- `requirements.txt` (structlog追加)
